// src/screens/main/food/foodStyles.js
import { StyleSheet } from 'react-native';

export const foodStyles = StyleSheet.create({
    markerCircle: {
        width: 44,
        height: 44,
        borderRadius: 22,
        borderWidth: 2.5,
        alignItems: 'center',
        justifyContent: 'center',
    },
    driverDot: {
        width: 18,
        height: 18,
        borderRadius: 9,
        borderWidth: 3,
    },
    backBtn: {
        position: 'absolute',
        left: 16,
        width: 42,
        height: 42,
        borderRadius: 21,
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: '#000',
        shadowOpacity: 0.18,
        shadowRadius: 8,
        shadowOffset: { width: 0, height: 2 },
        elevation: 8,
    },
    etaChip: {
        position: 'absolute',
        right: 16,
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 14,
        paddingVertical: 8,
        borderRadius: 20,
        shadowColor: '#000',
        shadowOpacity: 0.18,
        shadowRadius: 8,
        shadowOffset: { width: 0, height: 2 },
        elevation: 8,
    },
    etaTime: {
        fontSize: 17,
        fontWeight: '800',
        lineHeight: 20,
    },
    etaLabel: {
        fontSize: 10,
        color: 'rgba(120,120,140,0.9)',
        fontWeight: '600',
        letterSpacing: 0.4,
    },
    navFab: {
        position: 'absolute',
        right: 16,
        width: 52,
        height: 52,
        borderRadius: 26,
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: '#000',
        shadowOpacity: 0.3,
        shadowRadius: 10,
        shadowOffset: { width: 0, height: 4 },
        elevation: 10,
    },
    bottomSheet: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        borderTopLeftRadius: 28,
        borderTopRightRadius: 28,
        borderTopWidth: 1,
        paddingHorizontal: 20,
        paddingTop: 12,
        gap: 12,
    },
    dragHandle: {
        width: 36,
        height: 4,
        borderRadius: 2,
        backgroundColor: 'rgba(120,120,140,0.35)',
        alignSelf: 'center',
        marginBottom: 4,
    },
    statusRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        borderLeftWidth: 3,
        paddingLeft: 12,
    },
    stepTitle: {
        fontSize: 17,
        fontWeight: '700',
        letterSpacing: -0.2,
    },
    stepSubtitle: {
        fontSize: 13,
        marginTop: 2,
    },
});